'use client';

import React, { useState, useEffect } from 'react';
import { MessageSquare, Send, X, Sparkles, CheckCircle2, Copy, Check, FileText } from 'lucide-react';
import {
  WhatsAppTemplate,
  TemplateVariables,
  renderWhatsAppTemplate,
  buildWhatsAppSendUrl,
  DEFAULT_WHATSAPP_TEMPLATES
} from '@/lib/whatsapp-templates';

interface EnquiryItem {
  id: string;
  name: string;
  phone: string;
  location?: string;
  service?: string;
  status: 'pending' | 'contacted' | 'closed';
}

interface WhatsAppSendModalProps {
  enquiry: EnquiryItem;
  templates: WhatsAppTemplate[];
  onClose: () => void;
  onMarkContacted?: (enquiryId: string) => Promise<void>;
}

export default function WhatsAppSendModal({
  enquiry,
  templates,
  onClose,
  onMarkContacted
}: WhatsAppSendModalProps) {
  // Combine custom Firestore templates with built-in defaults if custom templates are sparse
  const allTemplates: WhatsAppTemplate[] =
    templates.length > 0
      ? templates
      : DEFAULT_WHATSAPP_TEMPLATES.map((t, idx) => ({ ...t, id: `default-${idx}` }));

  const [selectedTemplateIndex, setSelectedTemplateIndex] = useState<number>(0);
  const [customVars, setCustomVars] = useState<TemplateVariables>({
    customer_name: enquiry.name,
    phone: enquiry.phone,
    location: enquiry.location || 'AP & Telangana Branch',
    service: enquiry.service || 'Gold Valuation',
    gold_weight: '15.5g',
    purity: '22K (91.6% Hallmark)',
    offered_amount: '1,12,000',
    reference_id: `SCG-${enquiry.id.slice(0, 6).toUpperCase()}`
  });

  const [overriddenMessage, setOverriddenMessage] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);
  const [autoMarkStatus, setAutoMarkStatus] = useState<boolean>(true);

  const activeTmpl = allTemplates[selectedTemplateIndex] || allTemplates[0];
  const autoGeneratedMessage = activeTmpl ? renderWhatsAppTemplate(activeTmpl.content, customVars) : '';
  const currentMessage = overriddenMessage !== null ? overriddenMessage : autoGeneratedMessage;

  const handleTemplateSelect = (idx: number) => {
    setSelectedTemplateIndex(idx);
    setOverriddenMessage(null);
  };

  const handleVarUpdate = (key: keyof TemplateVariables, value: string) => {
    setCustomVars((prev) => ({ ...prev, [key]: value }));
    setOverriddenMessage(null);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(currentMessage);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSendWhatsApp = async () => {
    const url = buildWhatsAppSendUrl(enquiry.phone, currentMessage);
    window.open(url, '_blank', 'noopener,noreferrer');

    if (autoMarkStatus && enquiry.status === 'pending' && onMarkContacted) {
      await onMarkContacted(enquiry.id);
    }
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto font-sans text-slate-900">
      <div
        className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-2xl w-full p-6 sm:p-8 relative my-8 animate-in zoom-in-95 duration-200 flex flex-col gap-6"
        role="dialog"
        aria-labelledby="whatsapp-modal-title"
      >
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 text-slate-400 hover:text-slate-900 hover:bg-slate-100 rounded-full transition-colors cursor-pointer"
          aria-label="Close WhatsApp Composer"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Modal Header */}
        <div className="flex items-center gap-3 border-b border-slate-100 pb-4">
          <div className="w-10 h-10 rounded-xl bg-emerald-500 text-slate-950 flex items-center justify-center font-bold">
            <MessageSquare className="w-5 h-5" />
          </div>
          <div>
            <h3 id="whatsapp-modal-title" className="text-lg font-black text-slate-900">
              Send Stage-Based WhatsApp Message
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">
              Target Customer: <span className="font-bold text-slate-800">{enquiry.name}</span> ({enquiry.phone})
            </p>
          </div>
        </div>

        {/* Step 1: Select Template */}
        <div className="space-y-2">
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
            <FileText className="w-3.5 h-3.5 text-amber-600" />
            <span>Select Valuation Stage Template *</span>
          </label>

          <select
            value={selectedTemplateIndex}
            onChange={(e) => handleTemplateSelect(Number(e.target.value))}
            className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3.5 py-2.5 text-xs font-bold focus:outline-none focus:border-emerald-500 focus:bg-white text-slate-800 cursor-pointer"
          >
            {allTemplates.map((tmpl, idx) => (
              <option key={tmpl.id || idx} value={idx}>
                [{tmpl.stage}] {tmpl.title}
              </option>
            ))}
          </select>
        </div>

        {/* Step 2: Customize Stage Variables */}
        <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-black uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5 text-amber-500" />
              <span>Customize Valuation Stage Parameters</span>
            </span>
            <span className="text-[10px] text-slate-400 font-semibold">Auto-injected into template</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1">
                Gold Weight
              </label>
              <input
                type="text"
                value={customVars.gold_weight || ''}
                onChange={(e) => handleVarUpdate('gold_weight', e.target.value)}
                placeholder="e.g. 18.5g"
                className="w-full bg-white border border-slate-200 rounded-lg px-2.5 py-1.5 text-xs font-semibold text-slate-800 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div>
              <label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1">
                Purity
              </label>
              <input
                type="text"
                value={customVars.purity || ''}
                onChange={(e) => handleVarUpdate('purity', e.target.value)}
                placeholder="e.g. 22K (91.6%)"
                className="w-full bg-white border border-slate-200 rounded-lg px-2.5 py-1.5 text-xs font-semibold text-slate-800 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div>
              <label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1">
                Offered Payout (₹)
              </label>
              <input
                type="text"
                value={customVars.offered_amount || ''}
                onChange={(e) => handleVarUpdate('offered_amount', e.target.value)}
                placeholder="e.g. 1,35,000"
                className="w-full bg-white border border-slate-200 rounded-lg px-2.5 py-1.5 text-xs font-semibold text-slate-800 focus:outline-none focus:border-amber-500"
              />
            </div>
          </div>
        </div>

        {/* Step 3: Message Editor & WhatsApp Bubble Preview */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-700">
              Formatted Message Body (Editable)
            </label>
            <button
              type="button"
              onClick={handleCopy}
              className="text-[11px] text-slate-600 hover:text-slate-900 font-bold flex items-center gap-1 cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
              <span>{copied ? 'Copied!' : 'Copy Text'}</span>
            </button>
          </div>

          <textarea
            rows={7}
            value={currentMessage}
            onChange={(e) => setOverriddenMessage(e.target.value)}
            className="w-full bg-emerald-50/30 border border-emerald-200 rounded-xl p-3.5 text-xs text-slate-800 font-sans focus:outline-none focus:border-emerald-500 focus:bg-white leading-relaxed whitespace-pre-wrap"
          />
        </div>

        {/* Status Option */}
        {enquiry.status === 'pending' && (
          <label className="flex items-center gap-2 text-xs font-semibold text-slate-700 cursor-pointer">
            <input
              type="checkbox"
              checked={autoMarkStatus}
              onChange={(e) => setAutoMarkStatus(e.target.checked)}
              className="w-4 h-4 text-emerald-600 rounded border-slate-300 focus:ring-emerald-500"
            />
            <span>Automatically update enquiry status from &lsquo;Pending&rsquo; to &lsquo;Contacted&rsquo; when sending</span>
          </label>
        )}

        {/* Actions Footer */}
        <div className="flex items-center gap-3 justify-end pt-2 border-t border-slate-100">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold uppercase tracking-wider text-xs rounded-xl transition-colors cursor-pointer"
          >
            Cancel
          </button>

          <button
            type="button"
            onClick={handleSendWhatsApp}
            className="px-5 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white font-black uppercase tracking-wider text-xs rounded-xl transition-all shadow-md flex items-center gap-2 cursor-pointer"
          >
            <Send className="w-4 h-4" />
            <span>Open &amp; Send in WhatsApp</span>
          </button>
        </div>
      </div>
    </div>
  );
}
