import { SITE_URL } from './site-url';

export interface BranchHub {
  id: string;
  name: string;
  type: 'PHYSICAL_BRANCH';
  state: 'Andhra Pradesh' | 'Telangana';
  stateSlug: 'andhra-pradesh' | 'telangana';
  district: string;
  districtSlug: string;
  city: string;
  address: string;
  phone: string;
  timings: string;
  lat: number;
  lng: number;
  isFlagship?: boolean;
}

export const ALL_DISTRICT_BRANCH_HUBS: BranchHub[] = [
  // ==========================================
  // ANDHRA PRADESH (26 DISTRICT PHYSICAL HUBS)
  // ==========================================
  {
    id: 'ap-visakhapatnam',
    name: 'Akshaya Gold Buyers - Visakhapatnam District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Visakhapatnam',
    districtSlug: 'visakhapatnam',
    city: 'Visakhapatnam',
    address: 'Dwaraka Nagar 2nd Lane, Near Diamond Park & RTC Complex, Visakhapatnam, Andhra Pradesh - 530016',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 17.7289,
    lng: 83.3056,
    isFlagship: true
  },
  {
    id: 'ap-ntr-vijayawada',
    name: 'Akshaya Gold Buyers - NTR (Vijayawada) District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'NTR (Vijayawada)',
    districtSlug: 'ntr',
    city: 'Vijayawada',
    address: 'MG Road, Near Benz Circle & Trendset Mall, Vijayawada, Andhra Pradesh - 520010',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 16.5062,
    lng: 80.6480,
    isFlagship: true
  },
  {
    id: 'ap-guntur',
    name: 'Akshaya Gold Buyers - Guntur District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Guntur',
    districtSlug: 'guntur',
    city: 'Guntur',
    address: 'Brodipet 4/2 Main Road, Near Arundelpet & Railway Station, Guntur, Andhra Pradesh - 522002',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 16.3067,
    lng: 80.4365
  },
  {
    id: 'ap-kurnool',
    name: 'Akshaya Gold Buyers - Kurnool District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Kurnool',
    districtSlug: 'kurnool',
    city: 'Kurnool',
    address: 'Shop 4, Park Road, Near Raj Vihar Circle & Collectorate Road, Kurnool, Andhra Pradesh - 518001',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 15.8281,
    lng: 78.0373,
    isFlagship: true
  },
  {
    id: 'ap-nandyal',
    name: 'Akshaya Gold Buyers - Nandyal District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Nandyal',
    districtSlug: 'nandyal',
    city: 'Nandyal',
    address: 'Door 25/112, Sanjeeva Nagar Main Road, Near Gandhi Chowk, Nandyal, Andhra Pradesh - 518501',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 15.4875,
    lng: 78.4836
  },
  {
    id: 'ap-tirupati',
    name: 'Akshaya Gold Buyers - Tirupati District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Tirupati',
    districtSlug: 'tirupati',
    city: 'Tirupati',
    address: 'TK Street, Near Tirupati Railway Station & Old RTC Bus Stand, Tirupati, Andhra Pradesh - 517501',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 13.6288,
    lng: 79.4192
  },
  {
    id: 'ap-kakinada',
    name: 'Akshaya Gold Buyers - Kakinada District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Kakinada',
    districtSlug: 'kakinada',
    city: 'Kakinada',
    address: 'Main Road, Near Cinema Road Junction & Jagannaickpur, Kakinada, Andhra Pradesh - 533001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 16.9891,
    lng: 82.2475
  },
  {
    id: 'ap-east-godavari',
    name: 'Akshaya Gold Buyers - East Godavari (Rajahmundry) Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'East Godavari (Rajahmundry)',
    districtSlug: 'east-godavari',
    city: 'Rajahmundry',
    address: 'Main Road, Near Kotipalli Bus Stand & Kambalacheruvu, Rajamahendravaram, Andhra Pradesh - 533101',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 17.0005,
    lng: 81.8040
  },
  {
    id: 'ap-west-godavari',
    name: 'Akshaya Gold Buyers - West Godavari (Bhimavaram) Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'West Godavari (Bhimavaram)',
    districtSlug: 'west-godavari',
    city: 'Bhimavaram',
    address: 'J.P. Road, Near Someswara Temple Center, Bhimavaram, Andhra Pradesh - 534201',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 16.5449,
    lng: 81.5212
  },
  {
    id: 'ap-eluru',
    name: 'Akshaya Gold Buyers - Eluru District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Eluru',
    districtSlug: 'eluru',
    city: 'Eluru',
    address: 'Fire Station Road, Near R.R. Pet Commercial Center, Eluru, Andhra Pradesh - 534002',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 16.7107,
    lng: 81.0952
  },
  {
    id: 'ap-ananthapuramu',
    name: 'Akshaya Gold Buyers - Ananthapuramu District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Anantapur',
    districtSlug: 'ananthapuramu',
    city: 'Anantapur',
    address: 'Subhash Road, Near Tower Clock Circle & Saptagiri Circle, Anantapur, Andhra Pradesh - 515001',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 14.6819,
    lng: 77.6006
  },
  {
    id: 'ap-sri-sathya-sai',
    name: 'Akshaya Gold Buyers - Sri Sathya Sai (Puttaparthi) Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Sri Sathya Sai (Puttaparthi)',
    districtSlug: 'sri-sathya-sai',
    city: 'Puttaparthi',
    address: 'Main Chitravathi Road, Near Gopuram & Bus Stand, Puttaparthi, Andhra Pradesh - 515134',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 14.1652,
    lng: 77.8105
  },
  {
    id: 'ap-ysr-kadapa',
    name: 'Akshaya Gold Buyers - YSR Kadapa District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'YSR Kadapa',
    districtSlug: 'ysr-kadapa',
    city: 'Kadapa',
    address: 'Madras Road, Near Seven Roads Circle & RTC Complex, Kadapa, Andhra Pradesh - 516001',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 14.4673,
    lng: 78.8242
  },
  {
    id: 'ap-annamayya',
    name: 'Akshaya Gold Buyers - Annamayya (Rayachoti) District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Annamayya',
    districtSlug: 'annamayya',
    city: 'Rayachoti',
    address: 'Kadapa-Rayachoti Main Road, Near Old Bus Stand, Rayachoti, Andhra Pradesh - 516269',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 14.0573,
    lng: 78.7516
  },
  {
    id: 'ap-nellore',
    name: 'Akshaya Gold Buyers - SPSR Nellore District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Sri Potti Sriramulu Nellore',
    districtSlug: 'nellore',
    city: 'Nellore',
    address: 'Trunk Road, Near Gandhi Nagar & RTC Bus Stand, Nellore, Andhra Pradesh - 524001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 14.4426,
    lng: 79.9865
  },
  {
    id: 'ap-prakasam',
    name: 'Akshaya Gold Buyers - Prakasam (Ongole) District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Prakasam (Ongole)',
    districtSlug: 'prakasam',
    city: 'Ongole',
    address: 'Kurnool Road, Near Church Center & Rangarayudu Cheruvu, Ongole, Andhra Pradesh - 523002',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 15.5057,
    lng: 80.0499
  },
  {
    id: 'ap-bapatla',
    name: 'Akshaya Gold Buyers - Bapatla District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Bapatla',
    districtSlug: 'bapatla',
    city: 'Bapatla',
    address: 'GBC Road, Near Old Bus Stand & Light House Junction, Bapatla, Andhra Pradesh - 522101',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 15.9042,
    lng: 80.4676
  },
  {
    id: 'ap-palnadu',
    name: 'Akshaya Gold Buyers - Palnadu (Narasaraopet) Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Palnadu (Narasaraopet)',
    districtSlug: 'palnadu',
    city: 'Narasaraopet',
    address: 'Arundelpet Main Road, Near Clock Tower & Bus Complex, Narasaraopet, Andhra Pradesh - 522601',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 16.2359,
    lng: 80.0493
  },
  {
    id: 'ap-krishna',
    name: 'Akshaya Gold Buyers - Krishna (Machilipatnam) Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Krishna (Machilipatnam)',
    districtSlug: 'krishna',
    city: 'Machilipatnam',
    address: 'Koneru Center, Near Main Bazaar & District Court, Machilipatnam, Andhra Pradesh - 521001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 16.1875,
    lng: 81.1389
  },
  {
    id: 'ap-konaseema',
    name: 'Akshaya Gold Buyers - Dr. B.R. Ambedkar Konaseema (Amalapuram) Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Dr. B.R. Ambedkar Konaseema',
    districtSlug: 'konaseema',
    city: 'Amalapuram',
    address: 'Clock Tower Center, Near Red Bridge & Main Market, Amalapuram, Andhra Pradesh - 533201',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 16.5787,
    lng: 82.0061
  },
  {
    id: 'ap-chittoor',
    name: 'Akshaya Gold Buyers - Chittoor District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Chittoor',
    districtSlug: 'chittoor',
    city: 'Chittoor',
    address: 'High Road, Near Gandhi Statue & Old Bus Stand, Chittoor, Andhra Pradesh - 517001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 13.2172,
    lng: 79.1003
  },
  {
    id: 'ap-srikakulam',
    name: 'Akshaya Gold Buyers - Srikakulam District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Srikakulam',
    districtSlug: 'srikakulam',
    city: 'Srikakulam',
    address: 'GT Road, Near 7 Road Junction & Day & Night Hospital, Srikakulam, Andhra Pradesh - 532001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.2969,
    lng: 83.8968
  },
  {
    id: 'ap-vizianagaram',
    name: 'Akshaya Gold Buyers - Vizianagaram District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Vizianagaram',
    districtSlug: 'vizianagaram',
    city: 'Vizianagaram',
    address: 'MG Road, Near Clock Tower & Fort Road, Vizianagaram, Andhra Pradesh - 535002',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.1124,
    lng: 83.4022
  },
  {
    id: 'ap-parvathipuram-manyam',
    name: 'Akshaya Gold Buyers - Parvathipuram Manyam Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Parvathipuram Manyam',
    districtSlug: 'parvathipuram-manyam',
    city: 'Parvathipuram',
    address: 'Main Commercial Road, Near RTC Complex, Parvathipuram, Andhra Pradesh - 535501',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.7788,
    lng: 83.4286
  },
  {
    id: 'ap-anakapalli',
    name: 'Akshaya Gold Buyers - Anakapalli District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Anakapalli',
    districtSlug: 'anakapalli',
    city: 'Anakapalli',
    address: 'Main Road, Near Gavarapalem & RTC Bus Complex, Anakapalli, Andhra Pradesh - 531001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 17.6913,
    lng: 83.0039
  },
  {
    id: 'ap-alluri-sitharama-raju',
    name: 'Akshaya Gold Buyers - Alluri Sitharama Raju (Paderu) Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Andhra Pradesh',
    stateSlug: 'andhra-pradesh',
    district: 'Alluri Sitharama Raju',
    districtSlug: 'alluri-sitharama-raju',
    city: 'Paderu',
    address: 'Main Agency Road, Near ITDA Office & Complex, Paderu, Andhra Pradesh - 531024',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 7:30 PM (Mon - Sun)',
    lat: 18.0833,
    lng: 82.6667
  },

  // ==========================================
  // TELANGANA (33 DISTRICT PHYSICAL HUBS)
  // ==========================================
  {
    id: 'tg-hyderabad',
    name: 'Akshaya Gold Buyers - Hyderabad Central Flagship Branch',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Hyderabad',
    districtSlug: 'hyderabad',
    city: 'Hyderabad',
    address: 'Shop 102, Near Metro Station, Somajiguda & Punjagutta Main Road, Hyderabad, Telangana - 500082',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 17.4265,
    lng: 78.4528,
    isFlagship: true
  },
  {
    id: 'tg-medchal-malkajgiri',
    name: 'Akshaya Gold Buyers - Medchal-Malkajgiri Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Medchal-Malkajgiri',
    districtSlug: 'medchal-malkajgiri',
    city: 'Malkajgiri',
    address: 'Kukatpally Y Junction & Malkajgiri Main Road, Hyderabad, Telangana - 500072',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 17.4938,
    lng: 78.4018
  },
  {
    id: 'tg-ranga-reddy',
    name: 'Akshaya Gold Buyers - Ranga Reddy District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Ranga Reddy',
    districtSlug: 'ranga-reddy',
    city: 'Shamshabad',
    address: 'LB Nagar Ring Road & Shamshabad Airport Road, Hyderabad, Telangana - 500074',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 17.3457,
    lng: 78.5522
  },
  {
    id: 'tg-warangal',
    name: 'Akshaya Gold Buyers - Warangal District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Warangal',
    districtSlug: 'warangal',
    city: 'Warangal',
    address: 'J.P. Road, Near Chowrasta & Railway Gate, Warangal, Telangana - 506002',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 17.9689,
    lng: 79.5941
  },
  {
    id: 'tg-hanumakonda',
    name: 'Akshaya Gold Buyers - Hanumakonda District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Hanumakonda',
    districtSlug: 'hanumakonda',
    city: 'Hanumakonda',
    address: 'Nakkalagutta Main Road, Near Subedari & Collectorate, Hanumakonda, Telangana - 506001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 17.9975,
    lng: 79.5639
  },
  {
    id: 'tg-karimnagar',
    name: 'Akshaya Gold Buyers - Karimnagar District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Karimnagar',
    districtSlug: 'karimnagar',
    city: 'Karimnagar',
    address: 'Tower Circle Road, Near Collectorate & Bus Stand, Karimnagar, Telangana - 505001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 18.4386,
    lng: 79.1288
  },
  {
    id: 'tg-nizamabad',
    name: 'Akshaya Gold Buyers - Nizamabad District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Nizamabad',
    districtSlug: 'nizamabad',
    city: 'Nizamabad',
    address: 'Hyderabad Road, Near Khaleelwadi & Bus Station, Nizamabad, Telangana - 503001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 18.6725,
    lng: 78.0941
  },
  {
    id: 'tg-khammam',
    name: 'Akshaya Gold Buyers - Khammam District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Khammam',
    districtSlug: 'khammam',
    city: 'Khammam',
    address: 'Wyra Road, Near Old Bus Stand Circle & Mayuri Center, Khammam, Telangana - 507001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 17.2473,
    lng: 80.1514
  },
  {
    id: 'tg-mahabubnagar',
    name: 'Akshaya Gold Buyers - Mahabubnagar District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Mahabubnagar',
    districtSlug: 'mahabubnagar',
    city: 'Mahabubnagar',
    address: 'Station Road, Near Clock Tower & New Town, Mahabubnagar, Telangana - 509001',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 16.7488,
    lng: 78.0035
  },
  {
    id: 'tg-nalgonda',
    name: 'Akshaya Gold Buyers - Nalgonda District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Nalgonda',
    districtSlug: 'nalgonda',
    city: 'Nalgonda',
    address: 'Clock Tower Center, Near VT Colony & Bus Stand, Nalgonda, Telangana - 508001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:30 PM (Mon - Sun)',
    lat: 17.0575,
    lng: 79.2684
  },
  {
    id: 'tg-suryapet',
    name: 'Akshaya Gold Buyers - Suryapet District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Suryapet',
    districtSlug: 'suryapet',
    city: 'Suryapet',
    address: 'MG Road, Near Hyderabad-Vijayawada Highway, Suryapet, Telangana - 508213',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 17.1439,
    lng: 79.6239
  },
  {
    id: 'tg-siddipet',
    name: 'Akshaya Gold Buyers - Siddipet District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Siddipet',
    districtSlug: 'siddipet',
    city: 'Siddipet',
    address: 'Old Bus Stand Road, Near Mustabad Circle, Siddipet, Telangana - 502103',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.1018,
    lng: 78.8520
  },
  {
    id: 'tg-sangareddy',
    name: 'Akshaya Gold Buyers - Sangareddy District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Sangareddy',
    districtSlug: 'sangareddy',
    city: 'Sangareddy',
    address: 'Main Road, Near Old Collectorate & Bus Stand, Sangareddy, Telangana - 502001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 17.6190,
    lng: 78.0814
  },
  {
    id: 'tg-jagtial',
    name: 'Akshaya Gold Buyers - Jagtial District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Jagtial',
    districtSlug: 'jagtial',
    city: 'Jagtial',
    address: 'Tower Circle, Near Old Bus Stand & Commercial Road, Jagtial, Telangana - 505327',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.7942,
    lng: 78.9126
  },
  {
    id: 'tg-mancherial',
    name: 'Akshaya Gold Buyers - Mancherial District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Mancherial',
    districtSlug: 'mancherial',
    city: 'Mancherial',
    address: 'IB Chowk, Near Station Road & Bellampalli Road, Mancherial, Telangana - 504208',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.8679,
    lng: 79.4639
  },
  {
    id: 'tg-peddapalli',
    name: 'Akshaya Gold Buyers - Peddapalli District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Peddapalli',
    districtSlug: 'peddapalli',
    city: 'Peddapalli',
    address: 'Railway Station Road, Near Main Bazaar & Bus Depot, Peddapalli, Telangana - 505172',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.6163,
    lng: 79.3807
  },
  {
    id: 'tg-rajanna-sircilla',
    name: 'Akshaya Gold Buyers - Rajanna Sircilla District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Rajanna Sircilla',
    districtSlug: 'rajanna-sircilla',
    city: 'Sircilla',
    address: 'Gandhi Chowk, Near Cloth Market & Bypass, Sircilla, Telangana - 505405',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.3842,
    lng: 78.8048
  },
  {
    id: 'tg-kamareddy',
    name: 'Akshaya Gold Buyers - Kamareddy District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Kamareddy',
    districtSlug: 'kamareddy',
    city: 'Kamareddy',
    address: 'Station Road, Near NH 44 Bypass & Bus Complex, Kamareddy, Telangana - 503111',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.3219,
    lng: 78.3392
  },
  {
    id: 'tg-nirmal',
    name: 'Akshaya Gold Buyers - Nirmal District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Nirmal',
    districtSlug: 'nirmal',
    city: 'Nirmal',
    address: 'Gandhi Chowk, Near Mancherial Road Junction, Nirmal, Telangana - 504106',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 19.0964,
    lng: 78.3429
  },
  {
    id: 'tg-adilabad',
    name: 'Akshaya Gold Buyers - Adilabad District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Adilabad',
    districtSlug: 'adilabad',
    city: 'Adilabad',
    address: 'Cinema Road, Near Netaji Chowk & Bus Station, Adilabad, Telangana - 504001',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 19.6641,
    lng: 78.5320
  },
  {
    id: 'tg-komaram-bheem-asifabad',
    name: 'Akshaya Gold Buyers - Komaram Bheem Asifabad Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Komaram Bheem Asifabad',
    districtSlug: 'komaram-bheem-asifabad',
    city: 'Asifabad',
    address: 'Main Bazaar, Near Bus Stand & Collectorate Road, Asifabad, Telangana - 504293',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 7:30 PM (Mon - Sun)',
    lat: 19.3564,
    lng: 79.2818
  },
  {
    id: 'tg-jogulamba-gadwal',
    name: 'Akshaya Gold Buyers - Jogulamba Gadwal Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Jogulamba Gadwal',
    districtSlug: 'jogulamba-gadwal',
    city: 'Gadwal',
    address: 'Fort Road, Near Raichur Road Junction & Bus Stand, Gadwal, Telangana - 509125',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 16.2330,
    lng: 77.8047
  },
  {
    id: 'tg-wanaparthy',
    name: 'Akshaya Gold Buyers - Wanaparthy District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Wanaparthy',
    districtSlug: 'wanaparthy',
    city: 'Wanaparthy',
    address: 'Gandhi Chowk, Near Kothakota Road, Wanaparthy, Telangana - 509103',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 16.3624,
    lng: 78.0617
  },
  {
    id: 'tg-nagarkurnool',
    name: 'Akshaya Gold Buyers - Nagarkurnool District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Nagarkurnool',
    districtSlug: 'nagarkurnool',
    city: 'Nagarkurnool',
    address: 'ZP Road, Near Clock Tower & Bus Station, Nagarkurnool, Telangana - 509209',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 16.4854,
    lng: 78.3075
  },
  {
    id: 'tg-narayanpet',
    name: 'Akshaya Gold Buyers - Narayanpet District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Narayanpet',
    districtSlug: 'narayanpet',
    city: 'Narayanpet',
    address: 'Shivaji Chowk, Near Main Bazaar & Bus Stand, Narayanpet, Telangana - 509210',
    phone: '+91 88852 88817',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 16.7371,
    lng: 77.4984
  },
  {
    id: 'tg-vikarabad',
    name: 'Akshaya Gold Buyers - Vikarabad District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Vikarabad',
    districtSlug: 'vikarabad',
    city: 'Vikarabad',
    address: 'Station Road, Near NTR Chowk & Bus Complex, Vikarabad, Telangana - 501101',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 17.3364,
    lng: 77.9048
  },
  {
    id: 'tg-medak',
    name: 'Akshaya Gold Buyers - Medak District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Medak',
    districtSlug: 'medak',
    city: 'Medak',
    address: 'Ramdas Guda, Near Bus Depot & Cathedral Road, Medak, Telangana - 502110',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 18.0483,
    lng: 78.2618
  },
  {
    id: 'tg-jangaon',
    name: 'Akshaya Gold Buyers - Jangaon District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Jangaon',
    districtSlug: 'jangaon',
    city: 'Jangaon',
    address: 'Nehru Park Road, Near Station Road & Bus Complex, Jangaon, Telangana - 506167',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 17.7215,
    lng: 79.1558
  },
  {
    id: 'tg-mahabubabad',
    name: 'Akshaya Gold Buyers - Mahabubabad District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Mahabubabad',
    districtSlug: 'mahabubabad',
    city: 'Mahabubabad',
    address: 'Main Road, Near Railway Gate & Bus Stand, Mahabubabad, Telangana - 506101',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 17.5986,
    lng: 80.0039
  },
  {
    id: 'tg-bhadradri-kothagudem',
    name: 'Akshaya Gold Buyers - Bhadradri Kothagudem Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Bhadradri Kothagudem',
    districtSlug: 'bhadradri-kothagudem',
    city: 'Kothagudem',
    address: 'MG Road, Near Writer Basti & Bus Station, Kothagudem, Telangana - 507101',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 17.5501,
    lng: 80.6174
  },
  {
    id: 'tg-mulugu',
    name: 'Akshaya Gold Buyers - Mulugu District Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Mulugu',
    districtSlug: 'mulugu',
    city: 'Mulugu',
    address: 'NH 163, Near RTC Bus Stand & Collectorate Road, Mulugu, Telangana - 506343',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 7:30 PM (Mon - Sun)',
    lat: 18.1925,
    lng: 79.9392
  },
  {
    id: 'tg-jayashankar-bhupalpally',
    name: 'Akshaya Gold Buyers - Jayashankar Bhupalpally Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Jayashankar Bhupalpally',
    districtSlug: 'jayashankar-bhupalpally',
    city: 'Bhupalpally',
    address: 'Ambedkar Chowk, Near Main Road & Bus Stand, Bhupalpally, Telangana - 506169',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 7:30 PM (Mon - Sun)',
    lat: 18.4326,
    lng: 79.8631
  },
  {
    id: 'tg-yadadri-bhuvanagiri',
    name: 'Akshaya Gold Buyers - Yadadri Bhuvanagiri (Bhongir) Branch Hub',
    type: 'PHYSICAL_BRANCH',
    state: 'Telangana',
    stateSlug: 'telangana',
    district: 'Yadadri Bhuvanagiri',
    districtSlug: 'yadadri-bhuvanagiri',
    city: 'Bhuvanagiri',
    address: 'Station Road, Near Temple Highway & Bus Station, Bhuvanagiri, Telangana - 508116',
    phone: '+91 79974 33993',
    timings: '9:00 AM – 8:00 PM (Mon - Sun)',
    lat: 17.5113,
    lng: 78.8891
  }
];

export const BRAND = {
  name: 'Akshaya Gold Buyers',
  legalName: 'Akshaya Gold Buyers Enterprises',
  tagline: 'Transparent Gold Valuation • Zero Melting Loss XRF Testing • Instant Pledged Gold Release',
  shortDescription: 'Akshaya Gold Buyers provides transparent precious metals evaluation and instant payout across all 59 districts of Andhra Pradesh and Telangana. Certified non-destructive German XRF laser testing, live bullion market valuation, and bank-pledged gold loan settlement.',
  longDescription: 'Akshaya Gold Buyers is a trusted precious metal valuation and acquisition firm operating across Andhra Pradesh and Telangana, with dedicated physical branch hubs in all 59 district named cities. We provide scientific gold valuation using calibrated German XRF laser spectrometry with zero acid or melting loss, direct live bullion spot pricing, and specialized doorstep/bank escort assistance to release pledged gold loans.',
  phone1: '+917997433993',
  phone1Display: '+91 79974 33993',
  phone1Raw: '7997433993',
  phone2: '+918885288817',
  phone2Display: '+91 88852 88817',
  phone2Raw: '8885288817',
  whatsapp1: '917997433993',
  whatsapp2: '918885288817',
  whatsappDisplay: '+91 79974 33993 / +91 88852 88817',
  email: 'contact@akshayagoldbuyers.com',
  supportEmail: 'support@akshayagoldbuyers.com',
  website: SITE_URL,
  headOffice: {
    name: 'Akshaya Gold Buyers - Hyderabad Central Hub',
    street: 'Near Metro Station, Somajiguda & Punjagutta Main Road',
    city: 'Hyderabad',
    district: 'Hyderabad',
    state: 'Telangana',
    postalCode: '500082',
    country: 'IN'
  },
  branches: ALL_DISTRICT_BRANCH_HUBS,
  serviceHubs: [
    {
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      type: 'APPOINTMENT_ESCORT',
      description: 'Doorstep bank release and loan closure desk for Benz Circle, MG Road & One Town.'
    },
    {
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      type: 'APPOINTMENT_ESCORT',
      description: 'Doorstep bank release and evaluation team for Dwaraka Nagar, Gajuwaka & MVP Colony.'
    },
    {
      city: 'Warangal & Hanamkonda',
      state: 'Telangana',
      type: 'APPOINTMENT_ESCORT',
      description: 'Doorstep bank release and gold buying desk for Chowrasta, Kazipet & Subedari.'
    },
    {
      city: 'Kurnool & Nandyal',
      state: 'Andhra Pradesh',
      type: 'APPOINTMENT_ESCORT',
      description: 'Dedicated Rayalaseema gold assaying and bank loan takeover coordinators.'
    }
  ],
  operatingHours: 'Mon – Sun: 9:00 AM – 8:30 PM (All 7 Days Open)',
  foundedYear: '2016',
  stats: {
    totalLocations: 30620,
    apLocations: 18601,
    tgLocations: 12019,
    districts: 59,
    branchHubs: 59,
    happyCustomers: '1,50,000+',
    goldPurchasedKg: '8,500+ kg',
    rating: '4.9/5'
  },
  purityTesting: 'German XRF Spectrometric Laser Analysis (0% Acid, 0% Melting Loss, 100% Non-destructive)',
  weighingStandard: 'Class II Certified Digital Scales (0.001g Precision with Customer Display)',
  paymentModes: ['Direct Bank Transfer (IMPS / RTGS / NEFT)', 'UPI (PhonePe / Google Pay / Paytm)', 'Instant Cash Settlement (Subject to statutory KYC/PMLA limits)']
};

export function getBranchByDistrict(districtSlugOrName: string): BranchHub | undefined {
  const norm = districtSlugOrName.toLowerCase().trim();
  return ALL_DISTRICT_BRANCH_HUBS.find(
    b => b.districtSlug.toLowerCase() === norm ||
         b.district.toLowerCase() === norm ||
         b.city.toLowerCase() === norm ||
         b.id.toLowerCase() === norm
  );
}

export function getBranchesByState(stateSlug: 'andhra-pradesh' | 'telangana'): BranchHub[] {
  return ALL_DISTRICT_BRANCH_HUBS.filter(b => b.stateSlug === stateSlug);
}
